name: square_web_payments_example
description: A Widgetbook Flutter app for demonstrating the square_web_payments package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  square_web_payments:
    path: ../
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
