name: Build and deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --platform chrome
      - run: flutter pub get
        working-directory: example
      - run: flutter build web --base-href /square-web-payments/ --release
        working-directory: example
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: example/build/web
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
  publish:
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let pub_token = await core.getIDToken('https://pub.dev')
            core.exportVariable('PUB_TOKEN', pub_token)
      - run: flutter pub publish --dry-run
      - if: startsWith(github.ref, 'refs/tags/v0.0.')
        run: flutter pub publish --force
